apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/index.html
      name: html
      readOnly: true
  volumes:
  - name: html
    hostPath:
      # This file must exist on the node that this pod will be scheduled to
      path: /home/ec2-user/index.html
  # Hardcode the node that this pod will be scheduled to
  nodeName: ip-10-0-80-67.ec2.internal
