apiVersion: v1
kind: PersistentVolume
metadata:
  name: awselasticblockstore-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany 
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0b260d0838403d2fd
