apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcepersistentdisk-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany 
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb
