apiVersion: v1
kind: Pod
metadata:
  name: awselasticblockstore-volume-pod
spec:
  containers:
  - image: mongo
    name: mongodb
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
  volumes:
  - name: mongodb-data
    awsElasticBlockStore:
      volumeID: vol-0b260d0838403d2fd
  # Pod must be scheduled to node in same availability zone as the EBS volume
  nodeName: ip-10-0-36-80.ec2.internal
