apiVersion: v1
kind: Pod
metadata:
  name: gcepersistentdisk-volume-pod
spec:
  containers:
  - image: mongo
    name: mongodb
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
  volumes:
  - name: mongodb-data
    gcePersistentDisk:
      pdName: mongodb
